### ISSUE TITLE
Drawable / index 255 is out of bounds

### ISSUE THREAD

**Issue by cpmodding** [Skylumz/Sollumz#1018]
### 🔍 Issue Description

When importing a vehicle wheel mod, previously exported by Zmodeler, this error occurs:

`Error importing: C:\Users\test\Desktop\wheeltfstan\wheeltfstan_spt_01.ydr.xml 
 Traceback (most recent call last):
  File "C:\Users\test\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\sollumz_dev\sollumz_operators.py", line 95, in execute_timed
    import_ydr(filepath)
  File "C:\Users\test\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\sollumz_dev\ydr\ydrimport.py", line 37, in import_ydr
    return create_drawable_obj(ydr_xml, filepath, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\sollumz_dev\ydr\ydrimport.py", line 60, in create_drawable_obj
    model_objs = create_drawable_models(
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\sollumz_dev\ydr\ydrimport.py", line 75, in create_drawable_models
    model_datas = get_model_data(drawable_xml)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\sollumz_dev\ydr\model_data.py", line 32, in get_model_data
    mesh_data_lods={
                   ^
  File "C:\Users\test\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\sollumz_dev\ydr\model_data.py", line 33, in <dictcomp>
    lod_level: mesh_data_from_xml(model_xml) for lod_level, model_xml in model_lods.items()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\sollumz_dev\ydr\model_data.py", line 259, in mesh_data_from_xml
    vert_arr=get_model_joined_vert_arr(geoms),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\sollumz_dev\ydr\model_data.py", line 292, in get_model_joined_vert_arr
    apply_bone_ids(vert_arr, np.array(geom.bone_ids))
  File "C:\Users\test\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\sollumz_dev\ydr\model_data.py", line 323, in apply_bone_ids
    vert_arr["BlendIndices"] = bone_ids[vert_arr["BlendIndices"]]
                               ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: index 255 is out of bounds for axis 0 with size 1
`

Quick fixing it required to edit BlendWeights/BlendIndices values from `0 0 255 0` to `0 0 0 0`

### 🛠️ Sollumz Version(s)

2.5.0-dev-124350d3

### 🖥️ Blender Version(s)

4.2.0

### 🧩 Area

_No response_

### 🔄 Reproduction steps

1. Import .ydr.xml from attachment.
2. Blender will post an error log.

### 🎯 Expected Result

A properly imported vehicle wheel model.

### ⚠️ Current Result

A crash posted in the log above.

### 📎 Attachments

[wheeltfstan_spt_01.ydr.zip](https://github.com/user-attachments/files/17607974/wheeltfstan_spt_01.ydr.zip)

**Comment by alexguirre** [comment]
Why does it export it like that, `_ _ 255 _` indicates that it is skinned to the cloth mesh, for .ydd with .yld. The model doesn't even have an skeleton, the BlendIndices and BlendWeights are unnecessary.

But yeah, guess Sollumz should deal with these weird meshes.
