### ISSUE TITLE
Cant install addon

### ISSUE THREAD

**Issue by MrElvir** [Skylumz/Sollumz#111]
Traceback (most recent call last):
  File "C:\Users\MrElvir\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\Sollumz-main\__init__.py", line 32, in <module>
    import Sollumz
ModuleNotFoundError: No module named 'Sollumz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\MrElvir\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\Sollumz-main\__init__.py", line 34, in <module>
    raise ModuleNotFoundError(
ModuleNotFoundError: Sollumz module not found! Ensure the Sollumz folder is named 'Sollumz' (case-sensitive)!

**Comment by CFox04** [comment]
https://github.com/Skylumz/Sollumz/wiki/FAQs

**Comment by MrElvir** [comment]
Thank you
