### ISSUE TITLE
Export ydr error

### ISSUE THREAD

**Issue by Jouffluuu** [Skylumz/Sollumz#22]
Python: Traceback (most recent call last):

File "C:\Users\Thomas\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\Sollumz-main\ydrexport.py", line 1131, in execute result = write_ydr_xml(context, self.filepath)

File "C:\Users\Thomas\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\Sollumz-main\ydrexport.py", line 1071, in write_ydr_xml root = write_drawable(obj, filepath)

File "C:\Users\Thomas\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\Sollumz-main\ydrexport.py", line 1012, in write_drawable drawablemodels_node = write_drawablemodels_node(geometrys, materials, bones)

File "C:\Users\Thomas\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\Sollumz-main\ydrexport.py", line 409, in write_drawablemodels_node drawablemodels_high_node.append(write_model_node(high_models, materials, bones))

File "C:\Users\Thomas\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\Sollumz-main\ydrexport.py", line 352, in write_model_node vertex_str = get_vertex_string(obj_eval, vlayout, bones, depsgraph)

File "C:\Users\Thomas\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\Sollumz-main\ydrexport.py", line 228, in get_vertex_string layoutlist = order_vertex_list(tlist, vlayout)

File "C:\Users\Thomas\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\Sollumz-main\ydrexport.py", line 49, in order_vertex_list for i in range(len(vlayout)):

TypeError: object of type 'NoneType' has no len()

location: <unknown location>:-1

**Comment by Skylumz** [comment]
this plugin is WIP
