### ISSUE TITLE
'NoneType' object has no attribute 'vertices'. Trying to Export ydr.xml

### ISSUE THREAD

**Issue by Knaak53** [Skylumz/Sollumz#24]
Traceback (most recent call last):
  File "C:\Users\Manu\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\Sollumz-main\ydrexport.py", line 1131, in execute
    result = write_ydr_xml(context, self.filepath)
  File "C:\Users\Manu\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\Sollumz-main\ydrexport.py", line 1071, in write_ydr_xml
    root = write_drawable(obj, filepath)
  File "C:\Users\Manu\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\Sollumz-main\ydrexport.py", line 943, in write_drawable
    bbsphere = get_sphere_bb(children, bbminmax)
  File "C:\Users\Manu\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\Sollumz-main\ydrexport.py", line 910, in get_sphere_bb
    for vert in mesh.vertices:
AttributeError: 'NoneType' object has no attribute 'vertices'

location: <unknown location>:-1

**Comment by MrVicho13** [comment]
I have the same issue, if I import any .ydr from the game and I try to re-export it without touching anything I get the very same error.

**Comment by Skylumz** [comment]
update is on the way
