### ISSUE TITLE
import to blender issue 

### ISSUE THREAD

**Issue by Asteroidskyline** [Skylumz/Sollumz#242]
problem with import to blender 2.8-3.0
Importing file open only "empty" object and this message:

Error importing: C:\Users\aster\Desktop\felon_hi.yft.xml 
 Traceback (most recent call last):
  File "C:\Users\aster\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\Sollumz\sollumz_operators.py", line 59, in import_file
    import_yft(filepath)
  File "C:\Users\aster\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\Sollumz\yft\yftimport.py", line 209, in import_yft
    fragment_to_obj(yft_xml, filepath)
  File "C:\Users\aster\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\Sollumz\yft\yftimport.py", line 164, in fragment_to_obj
    materials = shadergroup_to_materials(
  File "C:\Users\aster\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\Sollumz\ydr\ydrimport.py", line 21, in shadergroup_to_materials
    material = create_shader(shader.name, shader.filename)
  File "C:\Users\aster\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\Sollumz\ydr\shader_materials.py", line 709, in create_shader
    raise AttributeError(f"Shader '{name}' does not exist!")
AttributeError: Shader 'hash_F9FB7331' does not exist!

**Comment by BrynnaDaRosa** [comment]
Anything prior to Blender 3.0 has been unsupported for some time now. Try using 3.0.
