### ISSUE TITLE
error when importing ybn files 

### ISSUE THREAD

**Issue by ANDREISTAIASA** [Skylumz/Sollumz#311]
when i try to import an ybn collision it gives me an error like this : Error importing: C:\Users\andre\OneDrive\Desktop\blender\cs6_01_4.ybn.xml 
 Traceback (most recent call last):
  File "C:\Users\andre\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\Sollumz\sollumz_operators.py", line 61, in import_file
    import_ybn(filepath)
  File "C:\Users\andre\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\Sollumz\ybn\ybnimport.py", line 366, in import_ybn
    composite_to_obj(ybn_xml, os.path.basename(
  File "C:\Users\andre\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\Sollumz\ybn\ybnimport.py", line 355, in composite_to_obj
    child_obj = bound_to_obj(child)
  File "C:\Users\andre\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\Sollumz\ybn\ybnimport.py", line 340, in bound_to_obj
    bvh = geometry_to_obj(bound, SollumType.BOUND_GEOMETRYBVH)
  File "C:\Users\andre\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\Sollumz\ybn\ybnimport.py", line 207, in geometry_to_obj
    poly_obj = poly_to_obj(
  File "C:\Users\andre\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\Sollumz\ybn\ybnimport.py", line 128, in poly_to_obj
    create_capsule(capsule.data, poly.radius, length / 2)
  File "C:\Users\andre\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\Sollumz\tools\meshhelper.py", line 108, in create_capsule
    bmesh.ops.create_uvsphere(
TypeError: create_uvsphere: keyword "diameter" is invalid for this operator

**Comment by d1n3301** [comment]
![image](https://user-images.githubusercontent.com/94755823/164003474-b730bb9f-4eda-40a4-9e9f-8c27c0b65e9c.png)
Everything works for me, use the latest version of CW and the version of the addon that I attached
https://github.com/Ekinoxx0/Sollumz/tree/dev
