### ISSUE TITLE
Doesnt work with blender 3.1.2

### ISSUE THREAD

**Issue by StrangeAnimal89** [Skylumz/Sollumz#312]
Hey,
when i install this addon to blender 3.1.2 and try to activate it, it reports as follows:

Traceback (most recent call last):

	File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\modules\addon_utils.py\", line 387, in enable mod.register()
	
	File "C:\Users\xxx\Roaming\Blender Foundation\Blender\3.1\scripts\addons\Sollumz-main\__init__.py", line 36, register auto_load.register()

	File "C:\Users\xxx\Roaming\Blender Foundation\Blender\3.1\scripts\addons\Sollumz-main\auto_load.py", line 37, in register bpy.utils.register_class(cls)

ValueError: register_class(...): allready registered as a subclass 'portalGizmoGroup'

**Comment by d1n3301** [comment]
What version of Sollumz are you installing?

**Comment by Hancapo** [comment]
Not a real issue, tested on Blender 3.1.2, using Sollumz [3614b45](https://github.com/Skylumz/Sollumz/commit/3614b45c0f393bdb3e457acb18db838d7af0b87a) and Sollumz (recommended version) [6e2ab97](https://github.com/Ekinoxx0/Sollumz/commit/6e2ab97dd1a3b2a6770d4834f4b2e7bce803b746) from https://github.com/Ekinoxx0/Sollumz/tree/dev
