### ISSUE TITLE
Importing

### ISSUE THREAD

**Issue by MistrzEnz0** [Skylumz/Sollumz#317]
Error importing: D:\Dokumenty\Projects\3z_warehouse\Model\id2_04_build14news.ydr.xml 
 Traceback (most recent call last):
  File "C:\Users\korne\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\Sollumz-main\sollumz_operators.py", line 65, in import_file
    import_ydr(filepath, self.import_settings)
  File "C:\Users\korne\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\Sollumz-main\ydr\ydrimport.py", line 604, in import_ydr
    filepath.replace(YDR.file_extension, '')), None, None, import_settings)
  File "C:\Users\korne\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\Sollumz-main\ydr\ydrimport.py", line 566, in drawable_to_obj
    model, materials, drawable.name, LODLevel.HIGH, bones, import_settings)
  File "C:\Users\korne\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\Sollumz-main\ydr\ydrimport.py", line 498, in drawable_model_to_obj
    create_tinted_shader_graph(child_obj)
  File "C:\Users\korne\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\Sollumz-main\ydr\shader_materials.py", line 137, in create_tinted_shader_graph
    tnt_ng = create_tinted_geometry_graph()
  File "C:\Users\korne\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\Sollumz-main\ydr\shader_materials.py", line 164, in create_tinted_geometry_graph
    sepxyz = gnt.nodes.new("GeometryNodeAttributeSeparateXYZ")
RuntimeError: Error: Node type GeometryNodeAttributeSeparateXYZ undefined

**Comment by d1n3301** [comment]
Blender 2.92 is not compatible, use 3.1.2 instead

**Comment by MistrzEnz0** [comment]
Okey thank you
