### ISSUE TITLE
importing ydd

### ISSUE THREAD

**Issue by lewiz18** [Skylumz/Sollumz#321]
Error importing: D:\gta modding\uppr_008_u.ydd.xml 
 Traceback (most recent call last):
  File "C:\Users\dripp\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\Sollumz-main\sollumz_operators.py", line 68, in import_file
    import_ydd(self, filepath, self.import_settings)
  File "C:\Users\dripp\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\Sollumz-main\ydd\yddimport.py", line 70, in import_ydd
    drawable_dict = drawable_dict_to_obj(ydd_xml, filepath, import_settings)
  File "C:\Users\dripp\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\Sollumz-main\ydd\yddimport.py", line 26, in drawable_dict_to_obj
    drawable_obj = drawable_to_obj(
  File "C:\Users\dripp\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\Sollumz-main\ydr\ydrimport.py", line 520, in drawable_to_obj
    materials = shadergroup_to_materials(drawable.shader_group, filepath)
  File "C:\Users\dripp\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\Sollumz-main\ydr\ydrimport.py", line 23, in shadergroup_to_materials
    material = create_shader(shader.name, shader.filename)
  File "C:\Users\dripp\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\Sollumz-main\ydr\shader_materials.py", line 780, in create_shader
    raise AttributeError(f"Shader '{name}' does not exist!")
AttributeError: Shader 'hash_83FB2C58' does not exist!

**Comment by lewiz18** [comment]
it works with mp models but not franklin

**Comment by Skylumz** [comment]
try reloading codewalker and re-exporting to .ydd.xml
