### ISSUE TITLE
Inability to skip over already converted material (auto convert for multiple models)

### ISSUE THREAD

**Issue by MoravianLion** [Skylumz/Sollumz#352]
When selecting multiple, duplicated models and using material auto convert feature, once the first model gets converted, the rest of duplicates such as model .001, model .002 are next, this results in error when Sollumz stops the whole procedure for the rest of object in the scene.

Adding some sort of an exception, when encountering already converted Sollumz material would be highly appreciated!

Blender info log

```
Error occured running operator : SOLLUMZ_OT_autoconvertmaterial 
 Traceback (most recent call last):
  File "C:\Users\MoravianLion\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Sollumz-main\sollumz_helper.py", line 27, in execute
    result = self.run(context)
  File "C:\Users\MoravianLion\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Sollumz-main\ydr\operators.py", line 85, in run
    new_material = convert_material(material)
  File "C:\Users\MoravianLion\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Sollumz-main\tools\drawablehelper.py", line 91, in convert_material
    raise Exception("Error can not convert a sollumz material.")
Exception: Error can not convert a sollumz material.

```

**Comment by CFox04** [comment]
Fixed in #378
