### ISSUE TITLE
Hello, could someone help me with this export error message?

### ISSUE THREAD

**Issue by AC3SKobra** [Skylumz/Sollumz#362]
Error exporting: C:\Users\xxx\OneDrive\Desktop\MLO\New folder\New Folder\ss1_07_vpr.ydr.xml 
 Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Sollumz-main\sollumz_operators.py", line 246, in export_object
    export_ydr(self, obj, filepath, self.export_settings)
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Sollumz-main\ydr\ydrexport.py", line 756, in export_ydr
    drawable_from_object(exportop, obj, filepath, None, None,
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Sollumz-main\ydr\ydrexport.py", line 721, in drawable_from_object
    drawable_model = drawable_model_from_object(
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Sollumz-main\ydr\ydrexport.py", line 434, in drawable_model_from_object
    geometry = geometry_from_object(
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Sollumz-main\ydr\ydrexport.py", line 374, in geometry_from_object
    obj, mesh = apply_and_triangulate_object(obj)
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Sollumz-main\ydr\ydrexport.py", line 345, in apply_and_triangulate_object
    mesh.calc_tangents()
RuntimeError: Error: Tangent space computation needs an UVMap, "(null)" not found, aborting

**Comment by dotpeak** [comment]
ask for support in the discord server - https://discord.gg/8N6DAuY5

**Comment by Hancapo** [comment]
ask for support in the discord server - https://discord.gg/8N6DAuY5
