### ISSUE TITLE
Error while Importing

### ISSUE THREAD

**Issue by HobbyScripter** [Skylumz/Sollumz#390]
Blender 3.2.2 from Windows Store
Sollumz Least Update from github Master branch.

Importing a Building over xml in Blender and crashing by ydr.

Error Code:
Error importing: F:\dt1_26_build_x\dt1_26_ground_decalc.ydr.xml 
 Traceback (most recent call last):
  File "C:\Users\ramon\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Sollumz-main\sollumz_operators.py", line 65, in import_file
    import_ydr(filepath, self.import_settings)
  File "C:\Users\ramon\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Sollumz-main\ydr\ydrimport.py", line 623, in import_ydr
    drawable = drawable_to_obj(ydr_xml, filepath, os.path.basename(
  File "C:\Users\ramon\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Sollumz-main\ydr\ydrimport.py", line 585, in drawable_to_obj
    dobj = drawable_model_to_obj(
  File "C:\Users\ramon\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Sollumz-main\ydr\ydrimport.py", line 518, in drawable_model_to_obj
    create_tinted_shader_graph(child_obj)
  File "C:\Users\ramon\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Sollumz-main\ydr\shader_materials.py", line 151, in create_tinted_shader_graph
    txt_node = geom.node_group.nodes["Image Texture"]
KeyError: 'bpy_prop_collection[key]: key "Image Texture" not found'

And Photo:
![grafik](https://user-images.githubusercontent.com/4710131/185742088-9e6a8966-c459-44f2-be22-4b50ec45b1ed.png)
and looks Normal
https://i.imgur.com/FZKo33H.jpeg

**Comment by theM4RI0** [comment]
what sollumz version (is it latest from github?) are you using?

**Comment by aspidemon** [comment]
I also get this error
![image](https://user-images.githubusercontent.com/96891562/191947821-b0a1e9d6-b8fa-40ae-be2e-96002b89a262.png)

**Comment by ooknumber13** [comment]
your hierarchy is messed up, check the wiki on proper hierarchy formats
