### ISSUE TITLE
Error when import car Wheel model

### ISSUE THREAD

**Issue by tracer8** [Skylumz/Sollumz#545]
Hi,
When i try to import car wheel model to blender, it trigger errors.
I uploaded yft file so you can check it out. 
[p1.yft.zip](https://github.com/Skylumz/Sollumz/files/10476179/p1.yft.zip)

Model car i take from here: 
[https://www.gta5-mods.com/vehicles/2014-mclaren-p1-fb28b756-465d-43e7-b4e0-9793bfa5f714](https://www.gta5-mods.com/vehicles/2014-mclaren-p1-fb28b756-465d-43e7-b4e0-9793bfa5f714)

![Screenshot 2023-01-23 09 15 16](https://user-images.githubusercontent.com/15725821/213955379-6feb6d8f-ad46-42c6-b103-53b048c7e1d9.png)

```Error importing: E:\Downloads\GTAExports\Cars\McLaren\p1.yft.xml 
 Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\Sollumz_Blender\sollumz_operators.py", line 74, in import_file
    import_yft(filepath, self)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\Sollumz_Blender\yft\yftimport.py", line 21, in import_yft
    yft_xml = YFT.from_xml_file(filepath)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\Sollumz_Blender\cwxml\fragment.py", line 25, in from_xml_file
    return Fragment.from_xml_file(filepath)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\Sollumz_Blender\cwxml\element.py", line 80, in from_xml_file
    return cls.from_xml(element_tree.getroot())
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\Sollumz_Blender\cwxml\element.py", line 103, in from_xml
    setattr(new, prop_name, type(obj_element).from_xml(child))
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\Sollumz_Blender\cwxml\drawable.py", line 593, in from_xml
    new = super().from_xml(element)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\Sollumz_Blender\cwxml\element.py", line 103, in from_xml
    setattr(new, prop_name, type(obj_element).from_xml(child))
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\Sollumz_Blender\cwxml\element.py", line 211, in from_xml
    new.value.append(new.list_type.from_xml(child))
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\Sollumz_Blender\cwxml\element.py", line 103, in from_xml
    setattr(new, prop_name, type(obj_element).from_xml(child))
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\Sollumz_Blender\cwxml\element.py", line 211, in from_xml
    new.value.append(new.list_type.from_xml(child))
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\Sollumz_Blender\cwxml\element.py", line 103, in from_xml
    setattr(new, prop_name, type(obj_element).from_xml(child))
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\Sollumz_Blender\cwxml\drawable.py", line 472, in from_xml
    new.data = list(map(lambda vert: vert_type(*vert), new.data))
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\Sollumz_Blender\cwxml\drawable.py", line 472, in <lambda>
    new.data = list(map(lambda vert: vert_type(*vert), new.data))
TypeError: <lambda>() missing 7 required positional arguments: 'blendweights', 'blendindices', 'normal', 'colour0', 'texcoord0', 'texcoord1', and 'tangent'
```

**Comment by CFox04** [comment]
Somehow the XML file you sent got malformed. Re-export the XML from CodeWalker and it should fix that issue. However, it brings up another issue because the vehicle windows have no shattermap in that vehicle for some reason. To fix this, delete the ``VehicleGlassWindows`` entry from the XML and you should be good to go. 
![image](https://user-images.githubusercontent.com/46362482/215118356-b342c214-28b8-4403-b762-0fca13463b5d.png)
delete all this ^
