### ISSUE TITLE
AttributeError: Shader 'hash_CC646720' does not exist!

### ISSUE THREAD

**Issue by 6frr** [Skylumz/Sollumz#550]
says this for every single file i try importing 

Error importing: C:\Users\eric\Documents\c\mp_m_freemode_01^hair_000_u.ydd.xml 
 Traceback (most recent call last):
  File "C:\Users\eric\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\Sollumz-main\sollumz_operators.py", line 71, in import_file
    import_ydd(self, filepath, self.import_settings)
  File "C:\Users\eric\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\Sollumz-main\ydd\yddimport.py", line 74, in import_ydd
    drawable_dict = drawable_dict_to_obj(ydd_xml, filepath, import_settings)
  File "C:\Users\eric\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\Sollumz-main\ydd\yddimport.py", line 30, in drawable_dict_to_obj
    drawable_obj = drawable_to_obj(
  File "C:\Users\eric\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\Sollumz-main\ydr\ydrimport.py", line 535, in drawable_to_obj
    materials = shadergroup_to_materials(drawable.shader_group, filepath)
  File "C:\Users\eric\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\Sollumz-main\ydr\ydrimport.py", line 29, in shadergroup_to_materials
    material = create_shader(filename)
  File "C:\Users\eric\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\Sollumz-main\ydr\shader_materials.py", line 748, in create_shader
    raise AttributeError(f"Shader '{filename}' does not exist!")
AttributeError: Shader 'hash_CC646720' does not exist!

**Comment by CFox04** [comment]
This is an issue with the file you exported from CodeWalker. For some reason the shader names are hashed. Make sure you have the latest version of CodeWalker, and if that doesn't work then ask for help in the CodeWalker discord.
