### ISSUE TITLE
Error when exporting XML

### ISSUE THREAD

**Issue by Napoz1** [Skylumz/Sollumz#556]
When i try to export a file as XML i get this error:

Error exporting: D:\desktop\3d modelling\prova felpa\jbib_001_u\jbib_001_u.001.ydd.xml 
 Traceback (most recent call last):
  File "C:\Users\andry\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\Sollumz\sollumz_operators.py", line 278, in export_object
    export_ydd(self, obj, filepath, self.export_settings)
  File "C:\Users\andry\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\Sollumz\ydd\yddexport.py", line 35, in export_ydd
    drawable_dict_from_object(exportop, obj, filepath,
  File "C:\Users\andry\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\Sollumz\ydd\yddexport.py", line 25, in drawable_dict_from_object
    drawable = drawable_from_object(
  File "C:\Users\andry\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\Sollumz\ydr\ydrexport.py", line 528, in drawable_from_object
    shaders = get_shaders_from_blender(obj)
  File "C:\Users\andry\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\Sollumz\ydr\ydrexport.py", line 33, in get_shaders_from_blender
    materials = get_used_materials(obj)
  File "C:\Users\andry\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\Sollumz\ydr\ydrexport.py", line 24, in get_used_materials
    if(mat.sollum_type == MaterialType.SHADER):
AttributeError: 'NoneType' object has no attribute 'sollum_type'

**Comment by ooknumber13** [comment]
read the error. your material isnt a sollumz shader.

**Comment by Hancapo** [comment]
💀💀💀💀

**Comment by CFox04** [comment]
You're using an outdated version of Sollumz. Make sure you download Sollumz from Github, not 5mods, and always ensure you are running the latest version before making an issue.
