### ISSUE TITLE
Updating to newest version throws error when activating

### ISSUE THREAD

**Issue by Cryzuz** [Skylumz/Sollumz#582]
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\modules\addon_utils.py", line 312, in enable
    importlib.reload(mod)
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\importlib\__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 619, in _exec
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Michael\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\Sollumz-main\__init__.py", line 31, in <module>
    auto_load.init()
  File "C:\Users\Michael\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\Sollumz-main\auto_load.py", line 24, in init
    modules = get_all_submodules(Path(__file__).parent)
  File "C:\Users\Michael\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\Sollumz-main\auto_load.py", line 58, in get_all_submodules
    return list(iter_submodules(directory, directory.name))
  File "C:\Users\Michael\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\Sollumz-main\auto_load.py", line 63, in iter_submodules
    yield importlib.import_module("." + name, package_name)
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Michael\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\Sollumz-main\yft\operators.py", line 5, in <module>
    from ..tools.blenderhelper import create_empty_object, get_children_recursive
ImportError: cannot import name 'create_empty_object' from 'Sollumz-main.tools.blenderhelper' (C:\Users\Michael\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\Sollumz-main\tools\blenderhelper.py)

**Comment by Cryzuz** [comment]
Fixed: Had to install Blender again. Installed it over the existing Blender Installation, so no uninstalling was required.
