### ISSUE TITLE
sollumz on blender 3.5 importing incorrect xml drawable

### ISSUE THREAD

**Issue by vmen007** [Skylumz/Sollumz#604]
sollumz on blender 3.5 importing incorrect xml drawable
id2_06_bub01.ydr

![Screenshot 2023-03-30 233341](https://user-images.githubusercontent.com/113604304/228837384-f11f8bc3-4dc2-469e-a34b-4f4dc9818727.png)
![3 5](https://user-images.githubusercontent.com/113604304/228837410-845efab6-ec29-493e-8a12-928fe18e6cac.jpg)

**Comment by coltfox** [comment]
We're working on updating Sollumz for Blender 3.5. For now, use 3.4.

**Comment by MoravianLion** [comment]
I have a feeling it might not be fixed yet. Same issue here, with the same model? I updated Sollumz today. Using Blender 3.5

`Error importing: C:\Users\MoravianLion\Desktop\del\delete_test\id2_06_bub01.ydr.xml 
 Traceback (most recent call last):
  File "C:\Users\MoravianLion\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\Sollumz-main\sollumz_operators.py", line 68, in import_file
    import_ydr(filepath, self.import_settings)
  File "C:\Users\MoravianLion\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\Sollumz-main\ydr\ydrimport.py", line 622, in import_ydr
    drawable = drawable_to_obj(ydr_xml, filepath, os.path.basename(
  File "C:\Users\MoravianLion\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\Sollumz-main\ydr\ydrimport.py", line 583, in drawable_to_obj
    dobj = drawable_model_to_obj(
  File "C:\Users\MoravianLion\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\Sollumz-main\ydr\ydrimport.py", line 513, in drawable_model_to_obj
    create_tinted_shader_graph(child_obj)
  File "C:\Users\MoravianLion\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\Sollumz-main\ydr\shader_materials.py", line 139, in create_tinted_shader_graph
    tnt_ng = create_tinted_geometry_graph()
  File "C:\Users\MoravianLion\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\Sollumz-main\ydr\shader_materials.py", line 180, in create_tinted_geometry_graph
    gnt.links.new(txtn.outputs[0], output.inputs[1])
IndexError: bpy_prop_collection[index]: index 1 out of range, size 1

`
