### ISSUE TITLE
Issue on export 

### ISSUE THREAD

**Issue by kilianf68** [Skylumz/Sollumz#627]
Good evening, 

When I use several materials for my EUP, for example (ped_emissive, ped and ped_alpha), everything works, but when exporting, I have an error that prevents me from finishing the job... and that is  well related to the fact that I have several materials.  

The error code:

`Error exporting: C:\Users\kilia\Desktop\EUP\Conversion\PORTE RADIO\radio_custom.ydd.xml
 Traceback (most recent call last):
  File "C:\Users\kilia\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\Sollumz-main\sollumz_operators.py", line 253, in export_object
    export_ydd(self, obj, filepath, self.export_settings)
  File "C:\Users\kilia\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\Sollumz-main\ydd\yddexport.py", line 35, in export_ydd
    drawable_dict_from_object(exportop, obj, filepath,
  File "C:\Users\kilia\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\Sollumz-main\ydd\yddexport.py", line 23, in drawable_dict_from_object
    drawable = drawable_from_object(
  File "C:\Users\kilia\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\Sollumz-main\ydr\ydrexport.py", line 817, in drawable_from_object
    drawable_model = drawable_model_from_object(
  File "C:\Users\kilia\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\Sollumz-main\ydr\ydrexport.py", line 493, in drawable_model_from_object
    geometries_to_join.append(duplicate_object(child))
  File "C:\Users\kilia\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\Sollumz-main\tools\blenderhelper.py", line 91, in duplicate_object
    return bpy.context.selected_objects[0]
IndexError: list index out of range`

How to do please ?

**Comment by ook3D** [comment]
this isnt a help forum. please dont make bug reports for stuff that isnt broken

**Comment by dotpeak** [comment]
the only thing here that's broken is your project. Post a message like this in the correct help channel in the [Discord server](https://discord.gg/cuhN9wJAfY).
