### ISSUE TITLE
Bound GeometryBVH can only have at most 32767 vertices 

### ISSUE THREAD

**Issue by wcsanshu** [Skylumz/Sollumz#640]
When I export the map, this error pops up. How can I solve it?

I must delete most of the models on the map to export it. How can I export my map in one go?

Error exporting: C:\Users\41582\Desktop\huitugou_2227_965.ydr.xml 
 Traceback (most recent call last):
  File "C:\Users\41582\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Sollumz-main\sollumz_operators.py", line 251, in export_object
    export_ydr(self, obj, filepath)
  File "C:\Users\41582\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Sollumz-main\ydr\ydrexport.py", line 848, in export_ydr
    drawable_from_object(exportop, obj, filepath, None,
  File "C:\Users\41582\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Sollumz-main\ydr\ydrexport.py", line 830, in drawable_from_object
    composite_from_object(child))
  File "C:\Users\41582\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Sollumz-main\ybn\ybnexport.py", line 373, in composite_from_object
    bound = bound_from_object(child)
  File "C:\Users\41582\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Sollumz-main\ybn\ybnexport.py", line 341, in bound_from_object
    return geometry_from_object(obj, SollumType.BOUND_GEOMETRYBVH, is_frag, export_settings)
  File "C:\Users\41582\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Sollumz-main\ybn\ybnexport.py", line 227, in geometry_from_object
    raise VerticesLimitError(
Sollumz-main.ybn.ybnexport.VerticesLimitError: Bound GeometryBVH can only have at most 32767 vertices!

**Comment by coltfox** [comment]
This is not a bug. As the error says "Bound GeometryBVH can only have at most 32767 vertices". You must split up the Bound GeometrtyBVH into multiple objects before exporting.

**Comment by Disquse** [comment]
This is a physical limitation of the game, you can't avoid it. If you're having so much polygons in a single bvh geometry I believe you have to reconsider a way how you're making collision, the game won't like it as well (poor performance and crashes is what would happen with you pretty often).

**Comment by wcsanshu** [comment]
I attempted to export a larger map model which consists of hundreds of objects. My question is, does the game limit a single model object to not exceed 32,767 vertices? Or is it that the total vertices of all models combined cannot exceed 32,767? Could you please answer this for me? I would be very grateful！！！

**Comment by wcsanshu** [comment]
> This is a physical limitation of the game, you can't avoid it. If you're having so much polygons in a single bvh geometry I believe you have to reconsider a way how you're making collision, the game won't like it as well (poor performance and crashes is what would happen with you pretty often). Collision geometry should be as simple as possible.

I attempted to export a larger map model which consists of hundreds of objects. My question is, does the game limit a single model object to not exceed 32,767 vertices? Or is it that the total vertices of all models combined cannot exceed 32,767? Could you please answer this for me? I would be very grateful
