### ISSUE TITLE
KeyError: 'bpy_prop_collection[key]: key "GeometryNodes" not found

### ISSUE THREAD

**Issue by wcsanshu** [Skylumz/Sollumz#649]
I encountered the following error when trying to import a character model: KeyError: 'bpy_prop_collection[key]: key "GeometryNodes" not found.

Error importing: C:\Users\41582\Desktop\xxs\Ultron Marvel Ultimate Alliance 3.ydd.xml 
 Traceback (most recent call last):
  File "C:\Users\41582\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Sollumz-main\sollumz_operators.py", line 71, in import_file
    import_ydd(self, filepath, self.import_settings)
  File "C:\Users\41582\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Sollumz-main\ydd\yddimport.py", line 74, in import_ydd
    drawable_dict = drawable_dict_to_obj(ydd_xml, filepath, import_settings)
  File "C:\Users\41582\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Sollumz-main\ydd\yddimport.py", line 30, in drawable_dict_to_obj
    drawable_obj = drawable_to_obj(
  File "C:\Users\41582\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Sollumz-main\ydr\ydrimport.py", line 592, in drawable_to_obj
    dobj = drawable_model_to_obj(
  File "C:\Users\41582\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Sollumz-main\ydr\ydrimport.py", line 522, in drawable_model_to_obj
    create_tinted_shader_graph(child_obj)
  File "C:\Users\41582\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Sollumz-main\ydr\shader_materials.py", line 140, in create_tinted_shader_graph
    geom = obj.modifiers["GeometryNodes"]
KeyError: 'bpy_prop_collection[key]: key "GeometryNodes" not found'

**Comment by coltfox** [comment]
Are you using Blender 3.4?
