### ISSUE TITLE
AttributeError: Shader 'hash_F9FB7331' does not exist!

### ISSUE THREAD

**Issue by Atuvi** [Skylumz/Sollumz#652]
Error importing: C:\Users\borow\Desktop\2017 Mercedes-Benz E300 Exclusive 4matic (W213) v2.0 by ahmeda1999\e300_hi.yft.xml 
 Traceback (most recent call last):
  File "C:\Users\borow\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\Sollumz-dev\sollumz_operators.py", line 71, in import_file
    import_yft(filepath, self.import_settings)
  File "C:\Users\borow\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\Sollumz-dev\yft\yftimport.py", line 275, in import_yft
    fragment_to_obj(yft_xml, filepath, import_settings)
  File "C:\Users\borow\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\Sollumz-dev\yft\yftimport.py", line 216, in fragment_to_obj
    materials = shadergroup_to_materials(
  File "C:\Users\borow\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\Sollumz-dev\ydr\ydrimport.py", line 21, in shadergroup_to_materials
    material = create_shader(shader.name, shader.filename)
  File "C:\Users\borow\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\Sollumz-dev\ydr\shader_materials.py", line 718, in create_shader
    raise AttributeError(f"Shader '{name}' does not exist!")
AttributeError: Shader 'hash_F9FB7331' does not exist!

So, my question is where can I find a shader like hash_F9FB7331?
Don't beat me I'm new to GTA 5 porting.

**Comment by ook3D** [comment]
you are trying to import a YFT made with zmodeler, which randomly hashes the shaders, also you shouldnt use the main sollumz branch for YFTs, you are asking for issues.

**Comment by Atuvi** [comment]
Bruh, I encountered a problem while using Blender and for your worries I remember to use Codewalker to decrypt files with extensions .yft, _hi.yft, and .yfd to XMLs. Every time I tried to import the yft.xml file, I encountered the same issue, with a different hash for each mod. Even when using the standard version (Sollmuz V1.1A), the problem persisted.
