### ISSUE TITLE
KeyError: 'bpy_prop_collection[key]: key "specularFalloffMult_y" not found'

### ISSUE THREAD

**Issue by TheJackalll** [Skylumz/Sollumz#655]
### I encountered this error when trying to export the ydr

Error exporting: F:\Fivem\pindu\kitchen.ydr.xml 
 Traceback (most recent call last):
  File "C:\Users\Axel Wilensjö\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\Sollumz-main\sollumz_operators.py", line 248, in export_object
    export_ydr(self, obj, filepath)
  File "C:\Users\Axel Wilensjö\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\Sollumz-main\ydr\ydrexport.py", line 837, in export_ydr
    drawable_from_object(exportop, obj, filepath, None,
  File "C:\Users\Axel Wilensjö\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\Sollumz-main\ydr\ydrexport.py", line 764, in drawable_from_object
    shaders = get_shaders_from_blender(materials)
  File "C:\Users\Axel Wilensjö\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\Sollumz-main\ydr\ydrexport.py", line 73, in get_shaders_from_blender
    y = material.node_tree.nodes[node.name[:-1] + "y"]
KeyError: 'bpy_prop_collection[key]: key "specularFalloffMult_y" not found'

**Comment by ook3D** [comment]
is your blender language set to something other than english

**Comment by TheJackalll** [comment]
No
![screenshot 2023-06-11 004521](https://github.com/Skylumz/Sollumz/assets/136203019/3b03e1df-8d18-46e4-b6f9-2a402f7a52ec)

**Comment by TheJackalll** [comment]
Wait I solved the problem now 😅
