### ISSUE TITLE
Can no longer import with 2.1

### ISSUE THREAD

**Issue by AliciaWindsor** [Skylumz/Sollumz#777]
Updated to 2.1 release and can no longer import ydd.xml from CodeWalker. Worked fine previously.

From the blender console:

ERROR: Error occured during creation of mesh 'jbib_013_u.model.002_high'! Is the mesh data valid?
Traceback (most recent call last):
  File "C:\Users\xxxx\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Sollumz\ydr\ydrimport.py", line 128, in create_lod_meshes
    lod_mesh = mesh_builder.build()
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Sollumz\ydr\mesh_builder.py", line 46, in build
    self.create_mesh_materials(mesh)
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Sollumz\ydr\mesh_builder.py", line 73, in create_mesh_materials
    mesh.attributes["material_index"].data.foreach_set(
KeyError: 'bpy_prop_collection[key]: key "material_index" not found'

**Comment by AliciaWindsor** [comment]
apologies. My Blender version was the issue. All good.
