### ISSUE TITLE
Icons break when disabling and enabling Sollumz

### ISSUE THREAD

**Issue by TheJackalll** [Skylumz/Sollumz#803]
Python: Traceback (most recent call last):
  File "C:\Users\Users\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\Sollumz-main\sollumz_ui.py", line 513, in draw_header
    icon_manager.icon_label("sollumz_icon", self)
  File "C:\Users\Users\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\Sollumz-main\icons.py", line 43, in icon_label
    return panel.layout.label(text="", icon_value=self.load_icon(name))
  File "C:\Users\Users\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\Sollumz-main\icons.py", line 32, in load_icon
    pcoll = self._preview_collections[PREVIEW_COLLECTION_NAME]
KeyError: 'main'

**Comment by alexguirre** [comment]
If you just enabled/updated the addon, try restarting Blender first.
