### ISSUE TITLE
Error when importing ydd.xml

### ISSUE THREAD

**Issue by FlyingFishstick** [Skylumz/Sollumz#829]
I get this error no matter what I try to import

`Error importing: C:\Users\lffes\OneDrive\Desktop\mp_m_freemode_01_mp_m_january2016^hand_001_u.ydd.xml 
 Traceback (most recent call last):
  File "C:\Users\lffes\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\Sollumz\sollumz_operators.py", line 55, in import_file
    import_ydd(filepath)
  File "C:\Users\lffes\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\Sollumz\ydd\yddimport.py", line 60, in import_ydd
    drawable_dict_to_obj(ydd_xml, filepath)
  File "C:\Users\lffes\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\Sollumz\ydd\yddimport.py", line 22, in drawable_dict_to_obj
    drawable_obj = drawable_to_obj(
  File "C:\Users\lffes\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\Sollumz\ydr\ydrimport.py", line 380, in drawable_to_obj
    materials = shadergroup_to_materials(drawable.shader_group, filepath)
  File "C:\Users\lffes\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\Sollumz\ydr\ydrimport.py", line 63, in shadergroup_to_materials
    format = TextureFormat[texture.format.replace(
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\enum.py", line 440, in __getitem__
    return cls._member_map_[name]
KeyError: '22'

`

**Comment by FlyingFishstick** [comment]
> Use the help channels in the discord. Github issues are for reporting actual bugs with the Sollumz plugin. & Use discord search before anything. This has been address many many times before. #689

thank you! I apologize for that
