### ISSUE TITLE
Shader Tools

### ISSUE THREAD

**Issue by aq233** [Skylumz/Sollumz#854]
Failed adding default.sps to Box_01_l because : 
 Traceback (most recent call last):
  File "C:\Users\1449473646\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\Sollumz\ydr\operators.py", line 450, in run
    self.create_material(context, obj, shader)
  File "C:\Users\1449473646\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\Sollumz\ydr\operators.py", line 427, in create_material
    mat = create_shader(shader)
  File "C:\Users\1449473646\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\Sollumz\ydr\shader_materials.py", line 1039, in create_shader
    create_basic_shader_nodes(builder)
  File "C:\Users\1449473646\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\Sollumz\ydr\shader_materials.py", line 839, in create_basic_shader_nodes
    bsdf.inputs["Specular IOR Level"].default_value = 0
KeyError: 'bpy_prop_collection[key]: key "Specular IOR Level" not found'

**Comment by ook3D** [comment]
your blender is outdated, read the requirements

please dont open an issue if you arent 110% certain it is a bug :)

**Comment by aq233** [comment]
> 您的搅拌机已过时，请阅读要求
> 
> 如果您不能 110% 确定这是一个错误:)请不要打开问题

My Blender version is 3.4.1
