### ISSUE TITLE
Importing Error.

### ISSUE THREAD

**Issue by Miatya** [Skylumz/Sollumz#856]
I'm having an error while trying to import a file into blender. This is the error I get.

Error importing: C:\Users\User\Documents\Development\Directory\Importing\2020 Ford F-450 Ambulance\f450ambo.yft.xml 
 Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Sollumz\sollumz_operators.py", line 97, in execute_timed
    import_yft(filepath)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Sollumz\yft\yftimport.py", line 34, in import_yft
    return create_fragment_obj(yft_xml, filepath,
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Sollumz\yft\yftimport.py", line 58, in create_fragment_obj
    materials = shadergroup_to_materials(
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Sollumz\ydr\ydrimport.py", line 224, in shadergroup_to_materials
    material = shader_item_to_material(shader, shader_group, filepath)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Sollumz\ydr\ydrimport.py", line 240, in shader_item_to_material
    material = create_shader(filename)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Sollumz\ydr\shader_materials.py", line 1042, in create_shader
    create_basic_shader_nodes(builder)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Sollumz\ydr\shader_materials.py", line 840, in create_basic_shader_nodes
    link_specular(b, spectex)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Sollumz\ydr\shader_materials.py", line 494, in link_specular
    links.new(spctex.outputs["Color"], bsdf.inputs["Specular"])
KeyError: 'bpy_prop_collection[key]: key "Specular" not found'

Note: I'm on Sollumz V2.2.0 and I'm using blender V4.0.2

**Comment by alexguirre** [comment]
Sollumz 2.2 doesn't support Blender 4.0. Downgrade Blender to 3.6 or update Sollumz to 2.3.1.
