### ISSUE TITLE
Error when exporting yft

### ISSUE THREAD

**Issue by Kilo-k** [Skylumz/Sollumz#870]
Error exporting: C:\Users\---\OneDrive\Documents\Blender\gta cars\deity\deity.yft.xml 
 Traceback (most recent call last):
  File "C:\Users\---\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Sollumz\sollumz_operators.py", line 183, in execute_timed
    success = export_yft(obj, filepath)
  File "C:\Users\---\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Sollumz\yft\yftexport.py", line 37, in export_yft
    frag_xml = create_fragment_xml(frag_obj, export_settings.auto_calculate_inertia,
  File "C:\Users\---\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Sollumz\yft\yftexport.py", line 75, in create_fragment_xml
    materials = get_sollumz_materials(frag_obj)
  File "C:\Users\---\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Sollumz\sollumz_helper.py", line 148, in get_sollumz_materials
    if mat.sollum_type != MaterialType.SHADER:
AttributeError: 'NoneType' object has no attribute 'sollum_type'

**Comment by ook3D** [comment]
this isnt a bug, you are missing sollumz shaders

**Comment by Kilo-k** [comment]
ok ill try and redo it
