### ISSUE TITLE
i got this error while instaling sollumz in blender

### ISSUE THREAD

**Issue by codeeditwithpranav** [Skylumz/Sollumz#871]
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\addonutils.py", line 351, in enable
    mod = import(module_name)
  File "C:\Users\HP\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\Sollumz_init.py", line 27, in <module>
    auto_load.init()
  File "C:\Users\HP\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\Sollumz\auto_load.py", line 24, in init
    modules = get_all_submodules(Path(file).parent)
  File "C:\Users\HP\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\Sollumz\autoload.py", line 58, in get_all_submodules
    return list(iter_submodules(directory, directory.name))
  File "C:\Users\HP\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\Sollumz\auto_load.py", line 63, in iter_submodules
    yield importlib.import_module("." + name, package_name)
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\importlib_init.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\HP\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\Sollumz\cwxml\drawable.py", line 5, in <module>
    from numpy.typing import NDArray
ModuleNotFoundError: No module named 'numpy.typing'

i got this error while instaling sollumz in blender

**Comment by alexguirre** [comment]
> Blender 2.93
You need Blender 4.0.
