### ISSUE TITLE
cant export ydr to codewalker xml?

### ISSUE THREAD

**Issue by Pigeonhunt3r** [Skylumz/Sollumz#894]
Error exporting: C:\Users\Morten\Desktop\mlo stuff\mosley\blend\sc1_34_mos.ydr.xml 
 Traceback (most recent call last):
  File "C:\Users\Morten\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\Sollumz-legacy\sollumz_operators.py", line 249, in export_object
    export_ydr(self, obj, filepath)
  File "C:\Users\Morten\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\Sollumz-legacy\ydr\ydrexport.py", line 837, in export_ydr
    drawable_from_object(exportop, obj, filepath, None,
  File "C:\Users\Morten\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\Sollumz-legacy\ydr\ydrexport.py", line 802, in drawable_from_object
    drawable_model = drawable_model_from_object(
  File "C:\Users\Morten\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\Sollumz-legacy\ydr\ydrexport.py", line 484, in drawable_model_from_object
    geometry = geometry_from_object(
  File "C:\Users\Morten\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\Sollumz-legacy\ydr\ydrexport.py", line 418, in geometry_from_object
    obj, mesh = apply_and_triangulate_object(obj)
  File "C:\Users\Morten\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\Sollumz-legacy\ydr\ydrexport.py", line 389, in apply_and_triangulate_object
    mesh.calc_tangents()
RuntimeError: Error: Tangent space computation needs a UV Map, "texcoord0" not found, aborting

**Comment by ook3D** [comment]
if you arent able to figure this issue out, you should not be using sollumz legacy tbh
